import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Activity, ArrowRight, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, Gamepad2, LayoutDashboard, LogIn, Palette, Pencil, Plus, Settings2, Trash2, Users, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const defaultSettings = { brandName: "PlayStation R2", tagline: "اللعب الحقيقي يبدأ من هنا", heroTitle: "ارفع مستوى لعبك", heroText: "صالة بلايستيشن مصممة للاعبين الذين يريدون شاشة أكبر، أجهزة أسرع، وتجربة لا تُنسى.", phone: "010 0000 0000", location: "القاهرة الجديدة · مفتوح يوميًا من 12 ظهرًا حتى 4 فجرًا", neonColor: "#E3293F", aboutText: "مساحة لعب فاخرة تجمع أحدث أجهزة PlayStation 5 مع أجواء تنافسية وخدمة سريعة." };
const emptyDevice = { name: "", category: "PlayStation 5", status: "available" as "available" | "busy" | "maintenance", singlePrice: 80, multiPrice: 120, quadPrice: 160, description: "" };
const statusText = { available: "متاح", busy: "مشغول", maintenance: "صيانة" } as const;
const bookingStatus = { pending: "قيد الانتظار", confirmed: "مؤكد", cancelled: "ملغي", completed: "مكتمل" } as const;
const modeText = { single: "فردي", multi: "ثنائي", quad: "رباعي" } as const;

function money(value: number) { return `${value.toLocaleString("ar-EG")} ج.م`; }

export default function Admin() {
  const utils = trpc.useUtils();
  const { data: adminLoggedIn, isLoading: checkingAdmin } = trpc.adminAuth.me.useQuery();
  const adminLogin = trpc.adminAuth.login.useMutation({ onSuccess: () => utils.adminAuth.me.invalidate() });
  const adminLogout = trpc.adminAuth.logout.useMutation({ onSuccess: () => utils.adminAuth.me.invalidate() });
  const [password, setPassword] = useState("");
  const { data: settings } = trpc.settings.get.useQuery(undefined, { enabled: Boolean(adminLoggedIn), refetchInterval: 3000 });
  const { data: devices = [] } = trpc.devices.list.useQuery(undefined, { enabled: Boolean(adminLoggedIn), refetchInterval: 3000 });
  const { data: bookings = [] } = trpc.bookings.list.useQuery(undefined, { enabled: Boolean(adminLoggedIn), refetchInterval: 3000 });
  const { data: stats } = trpc.dashboard.stats.useQuery(undefined, { enabled: Boolean(adminLoggedIn), refetchInterval: 3000 });
  const updateSettings = trpc.settings.update.useMutation({ onSuccess: () => { toast.success("تم حفظ إعدادات الموقع"); utils.settings.get.invalidate(); }, onError: error => toast.error(`تعذر حفظ البيانات: ${error.message}`) });
  const createDevice = trpc.devices.create.useMutation({ onSuccess: () => { toast.success("تمت إضافة الجهاز"); utils.devices.list.invalidate(); setDeviceForm(emptyDevice); }, onError: error => toast.error(`تعذر إضافة الجهاز: ${error.message}`) });
  const updateDevice = trpc.devices.update.useMutation({ onSuccess: () => { toast.success("تم تحديث الجهاز"); utils.devices.list.invalidate(); setEditingId(null); }, onError: error => toast.error(`تعذر تحديث الجهاز: ${error.message}`) });
  const removeDevice = trpc.devices.remove.useMutation({ onSuccess: () => { toast.success("تم حذف الجهاز والحجوزات المرتبطة به"); utils.devices.list.invalidate(); utils.bookings.list.invalidate(); utils.dashboard.stats.invalidate(); }, onError: error => toast.error(`تعذر حذف الجهاز: ${error.message}`) });
  const updateBooking = trpc.bookings.updateStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الحجز"); utils.bookings.list.invalidate(); utils.dashboard.stats.invalidate(); } });
  const removeBooking = trpc.bookings.remove.useMutation({ onSuccess: () => { toast.success("تم حذف الحجز"); utils.bookings.list.invalidate(); utils.dashboard.stats.invalidate(); }, onError: error => toast.error(`تعذر حذف الحجز: ${error.message}`) });
  const [active, setActive] = useState("overview");
  const [siteForm, setSiteForm] = useState(defaultSettings);
  const [deviceForm, setDeviceForm] = useState(emptyDevice);
  const [editingId, setEditingId] = useState<number | null>(null);
  useEffect(() => { if (settings) setSiteForm({ ...defaultSettings, ...settings }); }, [settings]);
  const neonStyle = { "--neon": siteForm.neonColor, "--neon-rgb": "227, 41, 63" } as React.CSSProperties;
  const saveSite = (event: React.FormEvent) => { event.preventDefault(); updateSettings.mutate(siteForm); };
  const saveDevice = (event: React.FormEvent) => { event.preventDefault(); if (!deviceForm.name || !deviceForm.description) return toast.error("أكمل بيانات الجهاز أولًا"); if (editingId) updateDevice.mutate({ ...deviceForm, id: editingId }); else createDevice.mutate(deviceForm); };

  const submitLogin = (event: React.FormEvent) => { event.preventDefault(); adminLogin.mutate({ password }, { onError: error => toast.error(error.message) }); };
  if (checkingAdmin) return <div className="admin-gate" dir="rtl"><Gamepad2 size={34} /><h1>جارٍ التحقق من لوحة الإدارة...</h1></div>;
  if (!adminLoggedIn) return <div className="admin-gate" dir="rtl"><span className="gate-icon"><Gamepad2 size={30} /></span><span className="section-kicker">R2 CONTROL CENTER</span><h1>دخول المدير</h1><p>هذه الصفحة خاصة بإدارة الصالة. أدخل كلمة السر المحلية للوصول.</p><form className="admin-login-form" onSubmit={submitLogin}><label>كلمة السر<input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="أدخل كلمة السر" /></label><button className="save-button" type="submit" disabled={adminLogin.isPending}><LogIn size={17} /> دخول لوحة الإدارة</button></form><Link href="/" className="gate-back"><ArrowRight size={15} /> العودة إلى الموقع</Link></div>;

  return <div dir="rtl" className="admin-shell" style={neonStyle}>
    <aside className="admin-sidebar"><Link href="/" className="admin-logo"><span className="brand-icon"><Gamepad2 size={20} /></span><span><b>PLAYSTATION R2</b><small>CONTROL CENTER</small></span></Link><div className="sidebar-label">WORKSPACE</div><nav>{[["overview", LayoutDashboard, "نظرة عامة"], ["devices", Gamepad2, "الأجهزة والغرف"], ["bookings", CalendarDays, "الحجوزات"], ["customize", Palette, "تخصيص الموقع"]].map(([key, Icon, label]) => <button key={key as string} className={active === key ? "side-item active" : "side-item"} onClick={() => setActive(key as string)}><Icon size={18} /><span>{label as string}</span>{active === key && <i />}</button>)}</nav><div className="sidebar-footer"><div className="admin-avatar">R2</div><div><b>مدير الصالة</b><small>ADMIN ACCESS</small></div><ChevronDown size={15} /></div></aside>
    <main className="admin-main"><header className="admin-topbar"><div><span className="breadcrumb">R2 HUB / CONTROL CENTER</span><h1>{active === "overview" ? "نظرة عامة" : active === "devices" ? "الأجهزة والغرف" : active === "bookings" ? "إدارة الحجوزات" : "تخصيص الموقع"}</h1></div><div className="top-actions"><Link href="/" className="preview-button"><Activity size={16} /> معاينة الموقع</Link><button className="preview-button" onClick={() => adminLogout.mutate()}><LogIn size={16} /> خروج</button><span className="admin-status"><i /> النظام يعمل</span></div></header>
      {active === "overview" && <Overview stats={stats} bookings={bookings} devices={devices} setActive={setActive} />}
      {active === "devices" && <Devices devices={devices} deviceForm={deviceForm} setDeviceForm={setDeviceForm} editingId={editingId} setEditingId={setEditingId} saveDevice={saveDevice} removeDevice={(id: number) => removeDevice.mutate({ id })} />}
      {active === "bookings" && <Bookings bookings={bookings} updateStatus={(id, status) => updateBooking.mutate({ id, status })} removeBooking={(id) => removeBooking.mutate({ id })} />}
      {active === "customize" && <Customize siteForm={siteForm} setSiteForm={setSiteForm} saveSite={saveSite} saving={updateSettings.isPending} />}
    </main>
  </div>;
}

function Overview({ stats, bookings, devices, setActive }: { stats?: { totalDevices: number; availableDevices: number; todayBookings: number; todayRevenue: number; occupancy: number }; bookings: any[]; devices: any[]; setActive: (key: string) => void }) {
  const cards = [{ label: "إيراد الحجوزات", value: money(stats?.todayRevenue ?? 0), icon: CircleDollarSign, trend: "+12.5%" }, { label: "حجوزات اليوم", value: stats?.todayBookings ?? 0, icon: CalendarDays, trend: "+8.2%" }, { label: "أجهزة متاحة", value: `${stats?.availableDevices ?? 0}/${stats?.totalDevices ?? 0}`, icon: Gamepad2, trend: "LIVE" }, { label: "نسبة الإشغال", value: `${stats?.occupancy ?? 0}%`, icon: Activity, trend: "هذا الأسبوع" }];
  return <><div className="dashboard-welcome"><div><span className="section-kicker">SATURDAY, 12 SEPTEMBER 2026</span><h2>أهلاً بك في مركز التحكم <span>يا كابتن.</span></h2><p>كل ما يحدث في R2 Hub تحت سيطرتك — لحظة بلحظة.</p></div><div className="welcome-mark"><span>R2</span><small>HUB</small></div></div><div className="metric-grid">{cards.map(card => <div className="metric-card" key={card.label}><div className="metric-icon"><card.icon size={20} /></div><span>{card.label}</span><strong>{card.value}</strong><small className={card.trend.startsWith("+") ? "positive" : "muted"}>{card.trend}</small></div>)}</div><div className="admin-grid-two"><section className="panel"><div className="panel-header"><div><span className="section-kicker">RECENT ACTIVITY</span><h3>آخر الحجوزات</h3></div><button onClick={() => setActive("bookings")} className="panel-link">عرض الكل <ArrowRight size={14} /></button></div><div className="booking-list">{bookings.slice(0, 4).map(booking => <div className="booking-row" key={booking.id}><div className="booking-avatar">{booking.customerName.slice(0, 1)}</div><div className="booking-name"><b>{booking.customerName}</b><small>{booking.deviceName} · {modeText[booking.playMode as keyof typeof modeText]}</small></div><div className="booking-time"><b>{booking.startTime}</b><small>{booking.bookingDate}</small></div><span className={`status-pill ${booking.status}`}>{bookingStatus[booking.status as keyof typeof bookingStatus]}</span></div>)}</div></section><section className="panel inventory-panel"><div className="panel-header"><div><span className="section-kicker">LIVE INVENTORY</span><h3>حالة الأجهزة</h3></div><button onClick={() => setActive("devices")} className="icon-button"><Settings2 size={17} /></button></div>{devices.map(device => <div className="inventory-row" key={device.id}><div><b>{device.name}</b><small>{device.category}</small></div><span className={`device-dot ${device.status}`} /> <span>{statusText[device.status as keyof typeof statusText]}</span></div>)}</section></div></>;
}

function Devices({ devices, deviceForm, setDeviceForm, editingId, setEditingId, saveDevice, removeDevice }: { devices: any[]; deviceForm: any; setDeviceForm: (value: any) => void; editingId: number | null; setEditingId: (value: number | null) => void; saveDevice: (event: React.FormEvent) => void; removeDevice: (id: number) => void }) {
  const edit = (device: any) => { setEditingId(device.id); setDeviceForm({ name: device.name, category: device.category, status: device.status, singlePrice: device.singlePrice, multiPrice: device.multiPrice, quadPrice: device.quadPrice, description: device.description }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className="content-stack"><section className="panel device-editor"><div className="panel-header"><div><span className="section-kicker">DEVICE & ROOM MANAGEMENT</span><h3>{editingId ? "تعديل الجهاز" : "إضافة جهاز أو غرفة"}</h3></div>{editingId && <button className="cancel-edit" onClick={() => { setEditingId(null); setDeviceForm(emptyDevice); }}><X size={15} /> إلغاء التعديل</button>}</div><form onSubmit={saveDevice} className="admin-form"><label>اسم الجهاز / الغرفة<input value={deviceForm.name} onChange={e => setDeviceForm({ ...deviceForm, name: e.target.value })} placeholder="مثال: VIP Room" /></label><label>النوع<input value={deviceForm.category} onChange={e => setDeviceForm({ ...deviceForm, category: e.target.value })} placeholder="PlayStation 5" /></label><label>الحالة<select value={deviceForm.status} onChange={e => setDeviceForm({ ...deviceForm, status: e.target.value })}><option value="available">متاح</option><option value="busy">مشغول</option><option value="maintenance">صيانة</option></select></label><label>سعر الفردي<input type="number" value={deviceForm.singlePrice} onChange={e => setDeviceForm({ ...deviceForm, singlePrice: Number(e.target.value) })} /></label><label>سعر الثنائي<input type="number" value={deviceForm.multiPrice} onChange={e => setDeviceForm({ ...deviceForm, multiPrice: Number(e.target.value) })} /></label><label>سعر الرباعي<input type="number" value={deviceForm.quadPrice} onChange={e => setDeviceForm({ ...deviceForm, quadPrice: Number(e.target.value) })} /></label><label className="wide">وصف يظهر للعميل<textarea value={deviceForm.description} onChange={e => setDeviceForm({ ...deviceForm, description: e.target.value })} placeholder="أضف مواصفات الجهاز وتجربته" /></label><button type="submit" className="save-button"><Plus size={17} /> {editingId ? "حفظ التعديل" : "إضافة للجرد"}</button></form></section><section className="panel"><div className="panel-header"><div><span className="section-kicker">CURRENT INVENTORY · {devices.length} ITEMS</span><h3>كل الأجهزة والغرف</h3></div></div><div className="table-wrap"><table><thead><tr><th>الجهاز</th><th>النوع</th><th>الأسعار / ساعة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{devices.map(device => <tr key={device.id}><td><div className="table-device"><span><Gamepad2 size={17} /></span><b>{device.name}</b></div></td><td>{device.category}</td><td><span className="price-chip">{device.singlePrice} / {device.multiPrice} / {device.quadPrice}</span></td><td><span className={`status-pill ${device.status}`}>{statusText[device.status as keyof typeof statusText]}</span></td><td><div className="row-actions"><button onClick={() => edit(device)}><Pencil size={15} /></button><button onClick={() => removeDevice(device.id)} className="danger"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div></section></div>;
}

function Bookings({ bookings, updateStatus, removeBooking }: { bookings: any[]; updateStatus: (id: number, status: "pending" | "confirmed" | "cancelled" | "completed") => void; removeBooking: (id: number) => void }) {
  return <div className="content-stack"><div className="metric-strip"><div><CalendarDays size={18} /><span>إجمالي الحجوزات</span><b>{bookings.length}</b></div><div><Clock3 size={18} /><span>قيد الانتظار</span><b>{bookings.filter(item => item.status === "pending").length}</b></div><div><CircleDollarSign size={18} /><span>القيمة الإجمالية</span><b>{money(bookings.reduce((sum, item) => sum + item.totalPrice, 0))}</b></div></div><section className="panel"><div className="panel-header"><div><span className="section-kicker">BOOKING MANAGEMENT</span><h3>كل الحجوزات القادمة</h3></div><span className="live-tag"><i /> تحديث تلقائي</span></div><div className="table-wrap"><table><thead><tr><th>العميل</th><th>الجهاز</th><th>الموعد</th><th>المدة</th><th>الإجمالي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{bookings.map(booking => <tr key={booking.id}><td><div className="table-customer"><span>{booking.customerName.slice(0, 1)}</span><div><b>{booking.customerName}</b><small>{booking.phone}</small></div></div></td><td>{booking.deviceName}<small className="table-sub">{modeText[booking.playMode as keyof typeof modeText]}</small></td><td><b>{booking.startTime}</b><small className="table-sub">{booking.bookingDate}</small></td><td>{booking.hours} ساعات</td><td><b className="neon-text">{money(booking.totalPrice)}</b></td><td><select className={`status-select ${booking.status}`} value={booking.status} onChange={e => updateStatus(booking.id, e.target.value as any)}>{Object.entries(bookingStatus).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></td><td><button className="table-delete" onClick={() => removeBooking(booking.id)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div></section></div>;
}

function Customize({ siteForm, setSiteForm, saveSite, saving }: { siteForm: any; setSiteForm: (value: any) => void; saveSite: (event: React.FormEvent) => void; saving: boolean }) {
  return <div className="customize-grid"><section className="panel"><div className="panel-header"><div><span className="section-kicker">BRAND & CONTENT</span><h3>بيانات الموقع العامة</h3></div><Palette size={20} className="panel-accent" /></div><form className="settings-form" onSubmit={saveSite}><label>اسم البراند<input value={siteForm.brandName} onChange={e => setSiteForm({ ...siteForm, brandName: e.target.value })} /></label><label>الجملة التعريفية<input value={siteForm.tagline} onChange={e => setSiteForm({ ...siteForm, tagline: e.target.value })} /></label><label>عنوان الـ Hero<input value={siteForm.heroTitle} onChange={e => setSiteForm({ ...siteForm, heroTitle: e.target.value })} /></label><label>رقم الهاتف<input value={siteForm.phone} onChange={e => setSiteForm({ ...siteForm, phone: e.target.value })} /></label><label className="wide">النص التعريفي الرئيسي<textarea value={siteForm.heroText} onChange={e => setSiteForm({ ...siteForm, heroText: e.target.value })} /></label><label className="wide">عن الصالة<textarea value={siteForm.aboutText} onChange={e => setSiteForm({ ...siteForm, aboutText: e.target.value })} /></label><label className="wide">العنوان ومواعيد العمل<input value={siteForm.location} onChange={e => setSiteForm({ ...siteForm, location: e.target.value })} /></label><div className="color-field"><label>لون النيون<input type="color" value={siteForm.neonColor} onChange={e => setSiteForm({ ...siteForm, neonColor: e.target.value })} /></label><code>{siteForm.neonColor}</code><span style={{ background: siteForm.neonColor }} /></div><button className="save-button" type="submit"><Check size={17} /> {saving ? "جارٍ الحفظ..." : "حفظ ونشر التغييرات"}</button></form></section><section className="custom-preview"><div className="preview-header"><span><i /> LIVE PREVIEW</span><Link href="/">فتح الموقع <ArrowRight size={14} /></Link></div><div className="preview-card" style={{ "--preview-neon": siteForm.neonColor } as React.CSSProperties}><div className="preview-brand"><Gamepad2 size={16} /> {siteForm.brandName}</div><span className="preview-kicker">{siteForm.tagline}</span><h2>{siteForm.heroTitle}</h2><p>{siteForm.heroText}</p><div className="preview-button">احجز الآن <ArrowRight size={14} /></div><div className="preview-glow" /></div><div className="sync-note"><Check size={16} /> أي تعديل تحفظه يظهر تلقائيًا للزوار في واجهة العميل.</div></section></div>;
}
